# Generated by Django 4.1 on 2024-08-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcustomers',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical customers', 'verbose_name_plural': 'historical customerss'},
        ),
    ]
