# Generated by Django 4.1 on 2024-08-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloans',
            name='contract_version',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='contract_version',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
