# Generated by Django 4.1 on 2024-08-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayments',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
